### ISSUE TITLE
Fix for: cmake-2.6 doesn't support negative index in string(SUBSTRING ...)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chrisburel/perlqt4#62]
```
What steps will reproduce the problem?
On centos-6, using cmake-2.6.4, I get the following error when trying to use 
cmake (using the f9f3e52f084c version of perl-Qt):

Make Error at CMakeLists.txt:91 (string):
  string end index: -1 is out of range 0 - 17

The attached patch fixes this problem.

```

Original issue reported on code.google.com by `olivier....@gmail.com` on 11 Jul 2014 at 9:45

Attachments:
* [perlqt4_cmake26.patch](https://storage.googleapis.com/google-code-attachments/perlqt4/issue-62/comment-0/perlqt4_cmake26.patch)

**Comment by chrisburel** [comment]
I applied this patch in 557d3536e6117266e2cc2aca0f8234f786590958.
